### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by LucanderP** [7CavArma3Dev/7Cav-Alive-Altis#341] opened 2020-06-19 06:21 UTC
**Map & Version**
Isla Duala and Lingor v 5.9 

**Description:**
massive frame drop when near town, probably because of mass spawn of ground units, infantry and Vehicles.

**Steps to reproduce:**
move to a big town and start shooting.

**Expected behavior:**
FPS should run above atleast 20 fps.

**Where did the issue occur?**
In-Game

**Additional context:**

**Screenshots:**

**Comment by Jaidendude** [comment] 2020-06-19 08:07
Please provide additional context;
- Solo on the server?
- If not, were all other players near you (Within 200m?)
- If not, where were they?

**Comment by LucanderP** [comment] 2020-06-19 13:35
1. More then 10 people on the server.
2. Spread out over a town and base. around 1000 m.
3. Some in AO (Big town) and some at Base.

This issue felt a lot like the one we had on Altis when it spawn a lot of groups at the same place.
(Too many AI and A10 spawns enemies #332)

**Comment by Jaidendude** [comment] 2020-06-19 14:31
When players are spread out this will cause more AI to spawn. This is a function of ALiVE as it will attempt to spawn all AI groups up to 1000 meters away from the nearest player.

Framerates can be increased by corralling players into an organised squad in a condensed area.

If this is the case of exceptional amounts of AI then a member of our public development staff will look into it.

**Comment by 7cavZlobinN** [comment] 2020-06-19 14:36
Known issue and duplicate of #327. Implemented a mitigation in #333 and will be deployed whenever the next patch gets deployed.

**Closed as completed by 7cavZlobinN** 2020-06-19 14:36 UTC
Labels: bug, Investigating, Mission Related
